version: "3.8"

services:
  db:
    container_name: seismic-risc-db
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - "5444:5432"
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  cache:
    container_name: seismic-risc-cache
    image: memcached:1.6.14-alpine
    networks:
      - internal

  api:
    container_name: seismic-risc-api
    build:
      context: ./api
    command: dockerize -wait tcp://db:5444 -timeout 90s
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./api:/code
    ports:
      - "8030:8030"
    depends_on:
      - db

  client:
    container_name: seismic-risc-client
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - ./client:/code
    ports:
      - "3030:3000"
    depends_on:
      - api

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    name: seismic-risc_pgdata
