name: API Pipeline

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
    paths:
      - 'api/requirements*.*'
      - 'api/**/*.py'
      - 'api/Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/api_pipeline.yml'

jobs:
  static_analysis:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Black with latest pip
      run: |
        python -m pip install --upgrade pip
        cat ./api/requirements-dev.txt | grep black== | cut -d' ' -f1 | xargs pip install

    - name: Check formatting with black
      run: |
        black --line-length 80 --target-version py37 --exclude migrations --check ./api

  tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./api/requirements-dev.txt

    - name: Run tests
      run: |
        cd ./api && pytest
